matrix: 
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: 10
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
    - os: linux
      language: node_js
      node_js: 10

    - os: linux
      dist: xenial
      language: minimal
      services:
        - docker
      env:
        - CROSS=1
        - CROSS_ARCH=armv7l
        - CROSS_IMAGE=arm32v7/node:10-stretch

    - os: windows
      language: node_js
      node_js: 10
      filter_secrets: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CROSS" ]; then
        docker run --rm --privileged hypriot/qemu-register
        docker create \
          -it --name cross \
          -v $(pwd):/home/node/app \
          -w /home/node/app \
          "$CROSS_IMAGE"
        docker start cross
        docker exec -it cross /bin/sh -c "apt update -y"
        docker exec -it cross /bin/sh -c "
          apt install -y \
            automake \
            gconf2 \
            gconf-service \
            libnotify4 \
            libappindicator1 \
            libxtst6 \
            libnss3 \
            libxext-dev \
            libxkbfile-dev \
            libxtst-dev
        "
        docker exec -it cross \
          /bin/sh -c "chown -R node:node /home/node/app"
        docker exec -it -u node cross \
          /bin/sh -c "npm install"
      else
        sudo apt-get install \
          automake \
          libgconf-2-4 \
          libtool \
          libxext-dev \
          libxkbfile-dev \
          libxtst-dev
      fi
    else
      npm uninstall --save mouse-forward-back
    fi

script:
  - |
    if [ "$CROSS" ]; then
      docker exec -it \
        -u node \
        -e CI="$CI" \
        -e DEBIAN_FRONTEND="$DEBIAN_FRONTEND" \
        -e TRAVIS_REPO_SLUG="$TRAVIS_REPO_SLUG" \
        -e TRAVIS_TAG="$TRAVIS_TAG" \
        -e GH_TOKEN="$GH_TOKEN" \
        cross \
        /bin/sh -c \
          "npm test && npm run dist -- --arch=${CROSS_ARCH}"
    else
      npm test && npm run dist
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
